server:
  port: 8081
spring:
  datasource:
    url: jdbc:h2:mem:merchantdb;MODE=MySQL;DB_CLOSE_DELAY=-1
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

app:
  rabbit:
    exchange: payments.exchange
    rk:
      created: payments.created
      status: payments.status
    queues:
      created: payments.created.q
      status: payments.status.q.merchant
